[package]
name = "HansenRegistry"
version = "1.0.0"
authors = ["Hansen Quantitative Systems"]

[addresses]
hansen = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
